In [1]:
import math
import asyncio.taskgroups
import asyncio.taskgroups
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


#no need to run any of this. data has already been changed.

# AAPL = pd.read_csv("../processed_data/AAPL_combined.csv")
# AMZN = pd.read_csv("../processed_data/AMZN_combined.csv")
# FB = pd.read_csv("../processed_data/FB_combined.csv")
# NVDA = pd.read_csv("../processed_data/NVDA_combined.csv")
# TSLA = pd.read_csv("../processed_data/TSLA_combined.csv")

# AAPL.head()
# AMZN.head()
# FB.head()
# NVDA.head()
# TSLA.head()

# ls = [AAPL, AMZN, FB, NVDA, TSLA]

In [ ]:
# # Drop columns using del as requested

# cols_to_drop = ['links', 'reshares', 'reshare_message', 'structurable']
# for i in ls:
#     for col in cols_to_drop:
#         if col in AAPL.columns:
#             del AAPL[col]

In [13]:
#don't run this

# AAPL.to_csv("AAPL_clean.csv",  index=False)
# AMZN.to_csv("AMZN_clean.csv",  index=False)
# FB.to_csv("FB_clean.csv",  index=False)
# NVDA.to_csv("NVDA_clean.csv",  index=False)
# TSLA.to_csv("TSLA_clean.csv",  index=False)

AAPL = pd.read_csv("AAPL_clean.csv")
AMZN = pd.read_csv("AMZN_clean.csv")
FB = pd.read_csv("FB_clean.csv")
NVDA = pd.read_csv("NVDA_clean.csv")
TSLA = pd.read_csv("TSLA_clean.csv")

AAPL.head(20)
AMZN.head(20)
FB.head(20)
NVDA.head(20)
TSLA.head(20)

C:\Users\jzweb\AppData\Local\Temp\ipykernel_16612\1148899197.py:9: DtypeWarning: Columns (0: owned_symbols) have mixed types. Specify dtype option on import or set low_memory=False.
  AAPL = pd.read_csv("AAPL_clean.csv")
C:\Users\jzweb\AppData\Local\Temp\ipykernel_16612\1148899197.py:10: DtypeWarning: Columns (0: owned_symbols) have mixed types. Specify dtype option on import or set low_memory=False.
  AMZN = pd.read_csv("AMZN_clean.csv")
C:\Users\jzweb\AppData\Local\Temp\ipykernel_16612\1148899197.py:11: DtypeWarning: Columns (0: owned_symbols) have mixed types. Specify dtype option on import or set low_memory=False.
  FB = pd.read_csv("FB_clean.csv")
C:\Users\jzweb\AppData\Local\Temp\ipykernel_16612\1148899197.py:12: DtypeWarning: Columns (0: owned_symbols, 1: structurable) have mixed types. Specify dtype option on import or set low_memory=False.
  NVDA = pd.read_csv("NVDA_clean.csv")
C:\Users\jzweb\AppData\Local\Temp\ipykernel_16612\1148899197.py:13: DtypeWarning: Columns (0: owned_symbols, 1: structurable) have mixed types. Specify dtype option on import or set low_memory=False.
  TSLA = pd.read_csv("TSLA_clean.csv")

,Unnamed: 0,id,body,created_at,user,source,symbols,mentioned_users,entities,links,likes,conversation,reshare_message,owned_symbols,reshares,structurable
0,14974,188017660,$TSLA 🤙,2019-12-24 20:45:19+00:00,"{'id': 561032, 'username': 'RichOnABoatInMaine...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,NaN,NaN,NaN,"['4', '1', '3', '0', '3', '0', '0', '0', '0', ...",NaN,NaN
1,14973,188017676,$TSLA it so painful holding puts over Xmas but...,2019-12-24 20:45:49+00:00,"{'id': 2025803, 'username': 'NeverGiveUpZ', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bearish'}},NaN,"{'total': 2, 'user_ids': [788054, 1226835]}","{'parent_message_id': 188017676, 'in_reply_to_...",NaN,"['27', '19', '8', '0', '8', '22', '0', '2', '0...",NaN,NaN
2,14972,188017707,$SHAK sorry Morgan Stanley your price targets ...,2019-12-24 20:46:39+00:00,"{'id': 1466616, 'username': 'ironwill21', 'nam...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'chart': {'thumb': 'https://charts.stocktwits...,NaN,"{'total': 7, 'user_ids': [202337, 2728220, 212...","{'parent_message_id': 188017707, 'in_reply_to_...",NaN,"['22', '18', '4', '0', '4', '26', '0', '0', '0...",NaN,NaN
3,14971,188017940,$TSLA oh boy! Going to ROCKET Thursday! 450 by...,2019-12-24 20:49:34+00:00,"{'id': 1550684, 'username': 'CheapAlmonds', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,"{'total': 4, 'user_ids': [572878, 1270136, 102...","{'parent_message_id': 188017940, 'in_reply_to_...",NaN,"['7', '6', '1', '0', '1', '10', '1', '2', '0',...",NaN,NaN
4,14970,188018067,$SPY $TSLA \n\nWhy is Tesla at 425?,2019-12-24 20:52:52+00:00,"{'id': 2199581, 'username': 'JAGXFriend', 'nam...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 7271, 'symbol': 'SPY', 'title': 'SPDR ...",[],{'sentiment': None},NaN,NaN,"{'parent_message_id': 188018067, 'in_reply_to_...",NaN,"['4', '3', '1', '0', '1', '2', '0', '1', '1', ...",NaN,NaN
5,14969,188018095,$TSLA This is why TESLA will always STAND OUT ...,2019-12-24 20:53:33+00:00,"{'id': 553222, 'username': 'ByGraceThruFaith',...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'chart': {'thumb': 'https://charts.stocktwits...,NaN,"{'total': 5, 'user_ids': [2728220, 1906472, 29...",NaN,NaN,"['12', '11', '0', '1', '1', '25', '0', '0', '0...",NaN,NaN
6,14968,188018197,$TSLA possibility that it&#39;s gonna run up i...,2019-12-24 20:55:52+00:00,"{'id': 260529, 'username': 'pewpewpewpewpew', ...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,NaN,NaN,NaN,"['2', '2', '0', '0', '0', '1', '0', '0', '0', ...",NaN,NaN
7,14967,188018202,$TSLA good look at new traffic visualizations...,2019-12-24 20:55:58+00:00,"{'id': 584870, 'username': 'holleryall', 'name...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},[{'title': 'Tesla Software 2019.40.50 -- First...,"{'total': 2, 'user_ids': [572878, 707393]}",NaN,NaN,"['19', '5', '14', '0', '14', '1', '1', '1', '1...",NaN,NaN
8,14966,188018268,$TSLA ride the open blue skies. Last time TESL...,2019-12-24 20:57:17+00:00,"{'id': 767238, 'username': 'Thankfulness', 'na...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,"{'total': 4, 'user_ids': [572878, 402859, 9944...",NaN,NaN,"['4', '1', '2', '1', '3', '2', '0', '0', '0', ...",NaN,NaN
9,14965,188018345,$TSLA I just shorted this. Have not felt mor...,2019-12-24 20:59:00+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,"{'total': 9, 'user_ids': [1117296, 2898340, 92...","{'parent_message_id': 188018345, 'in_reply_to_...",NaN,"['2', '2', '0', '0', '0', '0', '0', '1', '0', ...","{'reshared_count': 2, 'user_ids': [300819, 214...",NaN
10,14964,188018383,$TSLA Wow amazing,2019-12-24 21:00:06+00:00,"{'id': 1653555, 'username': 'StockSupra', 'nam...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,NaN,NaN,NaN,"['1', '1', '0', '0', '0', '0', '0', '0', '0', ...",NaN,NaN
11,14963,188018400,$TSLA you assume there will be no competition ...,2019-12-24 21:00:25+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,NaN,NaN,"{'reshared_count': 2, 'reshared_deleted': Fals...","['3', '2', '0', '2', '1', '1', '0', '1', '0', ...","{'reshared_count': 1, 'user_ids': [300819]}",NaN
12,14962,188018425,$TSLA 500 funding not neede,2019-12-24 21:00:55+00:00,"{'id': 873704, 'username': 'B127', 'name': 'Be...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,NaN,NaN,NaN,"['8', '7', '0', '1', '1', '4', '0', '0', '0', ...",NaN,NaN
13,14961,188018439,$TSLA 2 full days of trading left for this wee...,2019-12-24 21:01:13+00:00,"{'id': 636643, 'username': 'wezen20', 'name': ...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,NaN,NaN,NaN,"['39', '37', '1', '2', '2', '14', '0', '2', '0...",NaN,NaN
14,14960,188018444,$TSLA i think we will see 450 this year!,2019-12-24 21:01:18+00:00,"{'id': 644273, 'username': 'Gen10xer', 'name':...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,"{'total': 1, 'user_ids': [1502834]}",NaN,NaN,"['3', '3', '0', '0', '0', '5', '0', '0', '0', ...",NaN,NaN
15,14959,188018455,@OnTheClock @chesspiece @ign $TSLA hahahaha Ri...,2019-12-24 21:01:27+00:00,"{'id': 994434, 'username': 'dexteroustrader', ...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...","['@OnTheClock', '@chesspiece', '@ign']",{'sentiment': {'basic': 'Bullish'}},NaN,NaN,"{'parent_message_id': 188015534, 'in_reply_to_...",NaN,"['22', '7', '12', '4', '15', '21', '0', '0', '...",NaN,NaN
16,14958,188018490,$TSLA,2019-12-24 21:02:16+00:00,"{'id': 1706827, 'username': 'Budz', 'name': 'B...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'chart': {'thumb': 'https://charts.stocktwits...,NaN,"{'total': 2, 'user_ids': [994434, 2728220]}","{'parent_message_id': 188018490, 'in_reply_to_...",NaN,"['3', '1', '2', '0', '2', '1', '0', '0', '0', ...",NaN,NaN
17,14957,188018502,$TSLA Adam Jonas and a monkey flipping coins h...,2019-12-24 21:02:24+00:00,"{'id': 274615, 'username': 'AlphaAndOmega', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': {'basic': 'Bullish'}},NaN,"{'total': 3, 'user_ids': [994434, 2728220, 232...",NaN,NaN,"['28', '20', '4', '7', '8', '73', '1', '0', '0...","{'reshared_count': 1, 'user_ids': [274615]}",NaN
18,14956,188018513,$TSLA I see lots of happy longs but nobody cla...,2019-12-24 21:02:34+00:00,"{'id': 923493, 'username': 'mikeb2', 'name': '...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,"{'total': 1, 'user_ids': [452351]}","{'parent_message_id': 188018513, 'in_reply_to_...",NaN,"['31', '17', '14', '0', '14', '27', '0', '1', ...","{'reshared_count': 2, 'user_ids': [493222, 452...",NaN
19,14955,188018526,"$TSLA Thanks, should be interesting",2019-12-24 21:02:56+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],{'sentiment': None},NaN,NaN,NaN,"{'reshared_count': 1, 'reshared_deleted': Fals...","['4', '2', '0', '3', '2', '2', '0', '1', '0', ...",NaN,NaN

In [11]:
import ast

def clean_entities_sentiment(val):
    if pd.isna(val):
        return 0
    try:
        # Parse the string as a dictionary
        d = ast.literal_eval(val)
        
        # Check if 'sentiment' key exists
        if 'sentiment' in d:
            sentiment_data = d['sentiment']
            
            # If sentiment is None, return 0
            if sentiment_data is None:
                return 0
            
            # If sentiment is a dictionary, look for 'basic' key
            if isinstance(sentiment_data, dict):
                basic_sentiment = sentiment_data.get('basic')
                if basic_sentiment == 'Bullish':
                    return 1
                elif basic_sentiment == 'Bearish':
                    return -1
        
        # If we reach here, it's Neutral/None or unknown structure
        return 0
        
    except (ValueError, SyntaxError) as e:
        # Handle cases where the string isn't valid python literal
        return 0

# Apply to all dataframes
datasets = [AAPL, AMZN, FB, NVDA, TSLA]
dataset_names = ["AAPL", "AMZN", "FB", "NVDA", "TSLA"]

for df, name in zip(datasets, dataset_names):
    print(f"Processing {name}...")
    df['entities'] = df['entities'].apply(clean_entities_sentiment)
    print(f"Unique values in {name}['entities'] after cleaning: {df['entities'].unique()}")
    print("-" * 20)

# Verify the result on AAPL
print(AAPL[['entities']].head())

Processing AAPL...
Unique values in AAPL['entities'] after cleaning: [ 0  1 -1]
--------------------
Processing AMZN...
Unique values in AMZN['entities'] after cleaning: [ 0  1 -1]
--------------------
Processing FB...
Unique values in FB['entities'] after cleaning: [ 0  1 -1]
--------------------
Processing NVDA...
Unique values in NVDA['entities'] after cleaning: [ 0  1 -1]
--------------------
Processing TSLA...
Unique values in TSLA['entities'] after cleaning: [ 1 -1  0]
--------------------
   entities
0         0
1         0
2         1
3         1
4         0

In [12]:
AAPL.head(20)
AMZN.head(20)
FB.head(20)
NVDA.head(20)
TSLA.head(20)

,Unnamed: 0,id,body,created_at,user,source,symbols,mentioned_users,entities,links,likes,conversation,reshare_message,owned_symbols,reshares,structurable
0,14974,188017660,$TSLA 🤙,2019-12-24 20:45:19+00:00,"{'id': 561032, 'username': 'RichOnABoatInMaine...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,NaN,NaN,NaN,"['4', '1', '3', '0', '3', '0', '0', '0', '0', ...",NaN,NaN
1,14973,188017676,$TSLA it so painful holding puts over Xmas but...,2019-12-24 20:45:49+00:00,"{'id': 2025803, 'username': 'NeverGiveUpZ', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],-1,NaN,"{'total': 2, 'user_ids': [788054, 1226835]}","{'parent_message_id': 188017676, 'in_reply_to_...",NaN,"['27', '19', '8', '0', '8', '22', '0', '2', '0...",NaN,NaN
2,14972,188017707,$SHAK sorry Morgan Stanley your price targets ...,2019-12-24 20:46:39+00:00,"{'id': 1466616, 'username': 'ironwill21', 'nam...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 7, 'user_ids': [202337, 2728220, 212...","{'parent_message_id': 188017707, 'in_reply_to_...",NaN,"['22', '18', '4', '0', '4', '26', '0', '0', '0...",NaN,NaN
3,14971,188017940,$TSLA oh boy! Going to ROCKET Thursday! 450 by...,2019-12-24 20:49:34+00:00,"{'id': 1550684, 'username': 'CheapAlmonds', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 4, 'user_ids': [572878, 1270136, 102...","{'parent_message_id': 188017940, 'in_reply_to_...",NaN,"['7', '6', '1', '0', '1', '10', '1', '2', '0',...",NaN,NaN
4,14970,188018067,$SPY $TSLA \n\nWhy is Tesla at 425?,2019-12-24 20:52:52+00:00,"{'id': 2199581, 'username': 'JAGXFriend', 'nam...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 7271, 'symbol': 'SPY', 'title': 'SPDR ...",[],0,NaN,NaN,"{'parent_message_id': 188018067, 'in_reply_to_...",NaN,"['4', '3', '1', '0', '1', '2', '0', '1', '1', ...",NaN,NaN
5,14969,188018095,$TSLA This is why TESLA will always STAND OUT ...,2019-12-24 20:53:33+00:00,"{'id': 553222, 'username': 'ByGraceThruFaith',...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 5, 'user_ids': [2728220, 1906472, 29...",NaN,NaN,"['12', '11', '0', '1', '1', '25', '0', '0', '0...",NaN,NaN
6,14968,188018197,$TSLA possibility that it&#39;s gonna run up i...,2019-12-24 20:55:52+00:00,"{'id': 260529, 'username': 'pewpewpewpewpew', ...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,NaN,NaN,NaN,"['2', '2', '0', '0', '0', '1', '0', '0', '0', ...",NaN,NaN
7,14967,188018202,$TSLA good look at new traffic visualizations...,2019-12-24 20:55:58+00:00,"{'id': 584870, 'username': 'holleryall', 'name...","{'id': 2269, 'title': 'StockTwits Web', 'url':...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,[{'title': 'Tesla Software 2019.40.50 -- First...,"{'total': 2, 'user_ids': [572878, 707393]}",NaN,NaN,"['19', '5', '14', '0', '14', '1', '1', '1', '1...",NaN,NaN
8,14966,188018268,$TSLA ride the open blue skies. Last time TESL...,2019-12-24 20:57:17+00:00,"{'id': 767238, 'username': 'Thankfulness', 'na...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 4, 'user_ids': [572878, 402859, 9944...",NaN,NaN,"['4', '1', '2', '1', '3', '2', '0', '0', '0', ...",NaN,NaN
9,14965,188018345,$TSLA I just shorted this. Have not felt mor...,2019-12-24 20:59:00+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,"{'total': 9, 'user_ids': [1117296, 2898340, 92...","{'parent_message_id': 188018345, 'in_reply_to_...",NaN,"['2', '2', '0', '0', '0', '0', '0', '1', '0', ...","{'reshared_count': 2, 'user_ids': [300819, 214...",NaN
10,14964,188018383,$TSLA Wow amazing,2019-12-24 21:00:06+00:00,"{'id': 1653555, 'username': 'StockSupra', 'nam...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,NaN,NaN,NaN,"['1', '1', '0', '0', '0', '0', '0', '0', '0', ...",NaN,NaN
11,14963,188018400,$TSLA you assume there will be no competition ...,2019-12-24 21:00:25+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,NaN,NaN,"{'reshared_count': 2, 'reshared_deleted': Fals...","['3', '2', '0', '2', '1', '1', '0', '1', '0', ...","{'reshared_count': 1, 'user_ids': [300819]}",NaN
12,14962,188018425,$TSLA 500 funding not neede,2019-12-24 21:00:55+00:00,"{'id': 873704, 'username': 'B127', 'name': 'Be...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,NaN,NaN,NaN,"['8', '7', '0', '1', '1', '4', '0', '0', '0', ...",NaN,NaN
13,14961,188018439,$TSLA 2 full days of trading left for this wee...,2019-12-24 21:01:13+00:00,"{'id': 636643, 'username': 'wezen20', 'name': ...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,NaN,NaN,NaN,"['39', '37', '1', '2', '2', '14', '0', '2', '0...",NaN,NaN
14,14960,188018444,$TSLA i think we will see 450 this year!,2019-12-24 21:01:18+00:00,"{'id': 644273, 'username': 'Gen10xer', 'name':...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 1, 'user_ids': [1502834]}",NaN,NaN,"['3', '3', '0', '0', '0', '5', '0', '0', '0', ...",NaN,NaN
15,14959,188018455,@OnTheClock @chesspiece @ign $TSLA hahahaha Ri...,2019-12-24 21:01:27+00:00,"{'id': 994434, 'username': 'dexteroustrader', ...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...","['@OnTheClock', '@chesspiece', '@ign']",1,NaN,NaN,"{'parent_message_id': 188015534, 'in_reply_to_...",NaN,"['22', '7', '12', '4', '15', '21', '0', '0', '...",NaN,NaN
16,14958,188018490,$TSLA,2019-12-24 21:02:16+00:00,"{'id': 1706827, 'username': 'Budz', 'name': 'B...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,"{'total': 2, 'user_ids': [994434, 2728220]}","{'parent_message_id': 188018490, 'in_reply_to_...",NaN,"['3', '1', '2', '0', '2', '1', '0', '0', '0', ...",NaN,NaN
17,14957,188018502,$TSLA Adam Jonas and a monkey flipping coins h...,2019-12-24 21:02:24+00:00,"{'id': 274615, 'username': 'AlphaAndOmega', 'n...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],1,NaN,"{'total': 3, 'user_ids': [994434, 2728220, 232...",NaN,NaN,"['28', '20', '4', '7', '8', '73', '1', '0', '0...","{'reshared_count': 1, 'user_ids': [274615]}",NaN
18,14956,188018513,$TSLA I see lots of happy longs but nobody cla...,2019-12-24 21:02:34+00:00,"{'id': 923493, 'username': 'mikeb2', 'name': '...","{'id': 2095, 'title': 'StockTwits For Android ...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,"{'total': 1, 'user_ids': [452351]}","{'parent_message_id': 188018513, 'in_reply_to_...",NaN,"['31', '17', '14', '0', '14', '27', '0', '1', ...","{'reshared_count': 2, 'user_ids': [493222, 452...",NaN
19,14955,188018526,"$TSLA Thanks, should be interesting",2019-12-24 21:02:56+00:00,"{'id': 493222, 'username': 'jeff131415', 'name...","{'id': 1149, 'title': 'StockTwits for iOS', 'u...","[{'id': 8660, 'symbol': 'TSLA', 'title': 'Tesl...",[],0,NaN,NaN,NaN,"{'reshared_count': 1, 'reshared_deleted': Fals...","['4', '2', '0', '3', '2', '2', '0', '1', '0', ...",NaN,NaN